# Generated by Django 4.0.3 on 2022-03-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todo_task_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='todo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.todo'),
            preserve_default=False,
        ),
    ]
